-- Easy: Filtering and Sorting
-- Display all successful orders.
-- Show order_id, customer_id, order_date, and status.
-- Sort the results from the newest order to the oldest.

SELECT 
	o.order_id,
	o.customer_id,
	o.order_date,
	o.status
FROM ecommerce.orders AS o
WHERE o.status IN('paid','shipped')
ORDER BY o.order_date DESC;





-- Easy: GROUP BY
-- Calculate the number of orders for each status.
-- Show status and order_count.
-- Display the status with the highest number of orders first.


SELECT
	COUNT(DISTINCT o.order_id) AS order_count,
	o.status
FROM ecommerce.orders AS o
GROUP BY o.status
ORDER BY order_count DESC;






--  Easy: Date Aggregation
-- Calculate the total number of orders for each month.
-- Show order_month and order_count.
-- Sort the results chronologically from the oldest month to the newest.

SELECT
	DATE_TRUNC('month', o.order_date) AS order_month,
	COUNT(DISTINCT o.order_id) AS order_count
FROM ecommerce.orders AS o
GROUP BY order_month
ORDER BY order_month ASC;




--  Easy/Medium: JOIN and Revenue
-- Calculate the total amount of each successful order.
-- Show order_id, order_date, and order_total.
-- Display the order with the highest total amount first.

SELECT
	o.order_id,
	o.order_date,
	SUM(i.quantity * i.unit_price) AS order_total
FROM ecommerce.orders AS o
JOIN ecommerce.order_items AS i
	ON o.order_id = i.order_id
WHERE o.status IN ('paid' , 'shipped')
GROUP BY o.order_id, o.order_date
ORDER BY order_total DESC;



-- Medium: Three-Table JOIN and Aggregation
-- Calculate the total amount spent by each customer on successful orders.
-- Show customer_id, first_name, last_name, and total_spent.
-- Display the highest-spending customer first.

SELECT	
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(i.quantity * i.unit_price) AS total_spent
FROM ecommerce.customers AS c
JOIN ecommerce.orders AS o
	ON c.customer_id = o.customer_id
JOIN ecommerce.order_items AS i
	ON o.order_id = i.order_id
WHERE o.status IN ('paid' , 'shipped')
GROUP BY c.customer_id
ORDER BY total_spent DESC;






-- Medium: HAVING
-- Find customers who placed two or more successful orders.
-- Show customer_id, first_name, country, and order_count.
-- Display customers with the highest number of orders first.

SELECT
	c.customer_id,
	c.first_name,
	c.country,
	COUNT(DISTINCT o.order_id) AS order_count
FROM ecommerce.customers AS c
JOIN ecommerce.orders AS o
	ON c.customer_id = o.customer_id
JOIN ecommerce.order_items AS i
	ON o.order_id = i.order_id
WHERE o.status IN ('paid', 'shipped')
GROUP BY c.customer_id, c.first_name, c.country
HAVING COUNT(DISTINCT o.order_id) >= 2
ORDER BY order_count DESC;





-- Medium: Product Analysis
-- Calculate the total number of units sold for each product from successful orders.
-- Show product_id, product_name, and units_sold.
-- Display the best-selling product first.


SELECT
	p.product_name,
	p.product_id,
	SUM(i.quantity) AS units_sold
FROM ecommerce.products AS p
JOIN ecommerce.order_items AS i
	ON p.product_id = i.product_id
JOIN ecommerce.orders AS o
	ON i.order_id = o.order_id
WHERE o.status IN ('paid' , 'shipped')
GROUP BY p.product_name, p.product_id
ORDER BY units_sold DESC;





-- Medium: CASE
-- Segment products into three price categories:
-- price < 100: Low
-- price between 100 and 500: Medium
-- price > 500: High
-- Show product_id, product_name, price, and price_category.
-- Display the most expensive product first.

SELECT
	p.product_id,
	p.product_name,
	p.price,
	CASE
		WHEN price < 100 THEN 'low'
		WHEN price >= 100 AND price < 500 THEN 'medium'
		ELSE 'high'
	END AS price_category
FROM ecommerce.products AS p
ORDER BY price DESC;





-- Medium: Category Analysis
-- Calculate the total revenue generated by each category from successful orders.
-- Show category_name and total_revenue.
-- Display the category with the highest revenue first.

SELECT
	c.category_name,
	SUM(i.quantity * i.unit_price) AS total_revenue
FROM ecommerce.categories AS c
JOIN ecommerce.products AS p
	ON c.category_id = p.category_id
JOIN ecommerce.order_items AS i
	ON p.product_id = i.product_id
JOIN ecommerce.orders AS o
	ON i.order_id = o.order_id
WHERE o.status IN ('paid' , 'shipped')
GROUP BY c.category_name
ORDER BY total_revenue DESC;



-- Medium: Regional Analysis
-- Calculate the number of successful orders, unique active customers,
-- and total revenue for each country.
-- Show country, order_count, customer_count, and total_revenue.
-- Display the country with the highest revenue first.

SELECT
	c.country,
	COUNT(DISTINCT o.order_id) AS order_count,
	COUNT(DISTINCT c.customer_id) AS customer_count,
	SUM(i.quantity * i.unit_price) AS total_revenue
FROM ecommerce.customers AS c
JOIN ecommerce.orders AS o
	ON c.customer_id = o.customer_id
JOIN ecommerce.order_items AS i
	ON o.order_id = i.order_id
WHERE o.status IN ('paid','shipped')
GROUP BY c.country
ORDER BY total_revenue DESC;





-- Medium: CTE and Average Order Value
-- Calculate the average successful order value for each country.
-- Show country, order_count, and avg_order_value.
-- Display the country with the highest average order value first.


WITH order_totals  AS(
SELECT
	o.order_id,
	c.country,
	SUM(i.quantity * i.unit_price) AS total_revenue
FROM ecommerce.customers AS c
JOIN ecommerce.orders AS o
	ON c.customer_id = o.customer_id
JOIN ecommerce.order_items AS i
	ON o.order_id = i.order_id
WHERE o.status IN ('paid','shipped')
GROUP BY o.order_id, c.country
)
SELECT
	COUNT(DISTINCT order_id) AS order_count,
	country,
	ROUND(AVG(total_revenue),2) AS avg_order_value
FROM order_totals 
GROUP BY country
ORDER BY avg_order_value DESC;




-- Medium: CTE and Overall Average Comparison
-- Find customers whose total spending is higher than
-- the average spending of all active customers.
-- Show customer_id, first_name, country, total_spent,
-- and average_customer_spent.
-- Display the highest-spending customer first.

WITH all_customer AS(
SELECT
	COUNT(DISTINCT o.order_id) AS order_count,
	c.first_name,
	c.customer_id,
	c.country,
	SUM(i.quantity * i.unit_price) AS total_revenue
FROM ecommerce.order_items AS i
JOIN ecommerce.orders AS o
	ON i.order_id = o.order_id
JOIN ecommerce.customers AS c
	ON o.customer_id = c.customer_id
WHERE o.status IN ('paid','shipped')
GROUP BY c.first_name, c.customer_id, c.country
),
average_revenue AS(
SELECT
	AVG(total_revenue) AS total_avg
FROM all_customer
)
SELECT
	ac.first_name,
	ac.customer_id,
	ac.country,
	ac.total_revenue,
	ar.total_avg
FROM all_customer AS ac
CROSS JOIN average_revenue AS ar
WHERE ac.total_revenue > ar.total_avg
ORDER BY ac.total_revenue DESC;





-- Hard: Country Average Comparison
-- Find customers whose total spending is higher than
-- the average customer spending in their own country.
-- Show customer_id, first_name, country, total_spent,
-- and country_average.
-- Display the highest-spending customer first.

WITH country_avg AS(
SELECT
	c.first_name,
	c.customer_id,
	c.country,
	SUM(i.quantity * i.unit_price) AS total_revenue
FROM ecommerce.order_items AS i
JOIN ecommerce.orders AS o
	ON i.order_id = o.order_id
JOIN ecommerce.customers AS c
	ON o.customer_id = c.customer_id
WHERE o.status IN ('paid','shipped')
GROUP BY c.first_name, c.customer_id, c.country
),
avg_country_customer AS (
SELECT
	country,
	AVG(total_revenue) AS avg_total
FROM country_avg
GROUP BY country
)
SELECT	
	ca.first_name,
	ca.customer_id,
	ca.country,
	ca.total_revenue,
	acc.avg_total
FROM country_avg AS ca
JOIN avg_country_customer AS acc
	ON ca.country = acc.country
WHERE ca.total_revenue > acc.avg_total
ORDER BY ca.total_revenue DESC;




















